# Generated by Django 5.2.17 on 2026-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=512, unique=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('providers', models.ManyToManyField(related_name='search_caches', to='core.provider')),
            ],
        ),
    ]
