# Generated by Django 5.2.18 on 2026-10-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_providersearchcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_marked_at', models.DateTimeField(blank=True, null=True)),
                ('assumed_time', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='core.booking')),
            ],
            options={
                'ordering': ['appointment_at', 'id'],
            },
        ),
    ]
